# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 卮言
subtitle: 只能短暂 所以大嚷
description: 爱美食/看电影/自行车
keywords: [拖拖, shaoyaoqian, Hexo, blog, 博客, 卮言]
author: 拖拖
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
abbrlink:
  alg: crc16  # support crc16(default) and crc32
  rep: dec    # support dec(default) and hex
url: https://www.pengfeima.cn
root: /
permalink: posts/:category/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace: true
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: life
category_map:
  生活: life
  观点: observer
  笔记: notes
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime' # do not use file modified time as updated time

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
  - _posts/2023/template/*
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Minifier & Optimization plugin
## See: https://github.com/chenzhutian/hexo-all-minifier
html_minifier:
  silent: true
css_minifier:
  silent: true
js_minifier:
  silent: true
image_minifier:
  enable: false

# hexo-renderer-markdown-it
## See: https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration
markdown:
  langPrefix: 'language-'
  plugins:
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:shaoyaoqian/blog_underocean.git
  branch: main


github:
  repository: https://github.com/shaoyaoqian/blog_underocean
  branch: source


# Artalk
## Config: https://artalk.js.org
## Plugin: https://github.com/leirock/hexo-next-artalk
artalk:
  enable: true
  server: https://artalk.pengfeima.cn/
  jsUrl: https://artalk.pengfeima.cn/dist/Artalk.js
  cssUrl: https://artalk.pengfeima.cn/dist/Artalk.css
  commentCount: true
  pvCount: false
  darkMode: auto
  useBackendConf: true


# Search
search:
  path: search.xml
  field: post
  content: true
  format: html
