name: Publish Blog

on:
  push:
    branches:
      - source
  workflow_dispatch:

concurrency:
  group: "publish"
  cancel-in-progress: true

env:
  GIT_USER: shaoyaoqian
  GIT_EMAIL: mpf_npu@icloud.com

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch name
        run: |
          echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV
          
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: |
          cd hexo
          npm install

      - name: Configuration  git environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Deploy hexo
        run: |
          cd hexo
          npm run deploy